### ISSUE TITLE
Error when logout.

### ISSUE THREAD

**Issue by halojoy** [dotclear/dotclear#7]
First, I use SQLite for storage.
When I tried logout from admin I now have this error:
"Warning: session_destroy(): Session object destruction failed in C:\Apache24\htdocs\dotclear\inc\libs\clearbricks\session.db\class.session.db.php on line 117"
And now I can not get to the login screen!

**Comment by halojoy** [comment]
Here is complete ERROR message.
Note: everything works when I block out 117 //session_destroy()

`Warning: session_destroy(): Session object destruction failed in C:\Apache24\htdocs\dotclear\inc\libs\clearbricks\session.db\class.session.db.php on line 117

Fatal error: Uncaught Exception: unknown database 'dc_session' (1) in C:\Apache24\htdocs\dotclear\inc\libs\clearbricks\dblayer\class.sqlite.php:132 Stack trace: #0 C:\Apache24\htdocs\dotclear\inc\libs\clearbricks\dblayer\class.sqlite.php(144): sqliteConnection->db_query(Object(PDO), 'VACUUM 'dc_sess...') #1 C:\Apache24\htdocs\dotclear\inc\libs\clearbricks\dblayer\dblayer.php(397): sqliteConnection->db_exec(Object(PDO), 'VACUUM 'dc_sess...') #2 C:\Apache24\htdocs\dotclear\inc\libs\clearbricks\dblayer\class.sqlite.php(270): dbLayer->execute('VACUUM 'dc_sess...') #3 C:\Apache24\htdocs\dotclear\inc\libs\clearbricks\session.db\class.session.db.php(242): sqliteConnection->vacuum('dc_session') #4 C:\Apache24\htdocs\dotclear\inc\libs\clearbricks\session.db\class.session.db.php(218): sessionDB->_optimize() #5 [internal function]: sessionDB->_destroy('e150914c6045297...') #6 C:\Apache24\htdocs\dotclear\inc\libs\clearbricks\session.db\class.session.db.php(117): session_destroy() #7 C:\Apache24\htdocs\dotclear\admin\index.php(42): se in C:\Apache24\htdocs\dotclear\inc\libs\clearbricks\dblayer\class.sqlite.php on line 132`
